### ISSUE TITLE
python >=3.10.8 breaks plotting in igakit

### ISSUE THREAD

**Issue by elbert5770** [dalcinl/igakit#3]
Simple example from docs works perfectly in python <=3.10.6, but throws error in >=3.10.8.  I don't have 3.10.7 so I can't test that.

```
from igakit.cad import circle
from numpy import pi 
c1 = circle(angle=(0,pi/2.))
print(c1.knots)
print(c1.control)
c2 = circle(radius=2,angle=(0,pi/2.))
from igakit.plot import plt
plt.curve(c1,color='b')
plt.curve(c2,color='g')
plt.show()
```

Error:
```
Traceback (most recent call last):
  File "/home/elbert5770/Documents/python/igakit_test.py", line 8, in <module>
    plt.curve(c1,color='b')
  File "/home/elbert5770/.local/lib/python3.10/site-packages/igakit/plot.py", line 213, in curve
    crv = self.backend.line3d(lines=lines, **options)
  File "/home/elbert5770/.local/lib/python3.10/site-packages/igakit/plot_mpl.py", line 67, in line3d
    ax = gca()
  File "/home/elbert5770/.local/lib/python3.10/site-packages/igakit/plot_mpl.py", line 19, in gca
    return gcf().gca(projection='3d', **kwargs)
TypeError: FigureBase.gca() got an unexpected keyword argument 'projection'
```

**Comment by dalcinl** [comment]
I don't think this is a problem related to Python version. What are the the matplotlib versions you are using in each case?

**Comment by elbert5770** [comment]
python 3.10.8 = matplotlib 3.7.1
python 3.10.6 = matplotlib 3.5.1

Here it says for matplotlib 3.6: The following arguments have been removed: Keyword arguments to gca(); there is no replacement.
https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html

**Comment by dalcinl** [comment]
@elbert5770 Could you please try whether the fix I pushed to master works on your side?

**Comment by elbert5770** [comment]
Yes, it does work, thank you.
